### ISSUE TITLE
Add release tags

### ISSUE THREAD

**Issue by johnjohndoe** [mkroman/rar#3]
Please maintain consistent releases by also adding Git tags and pushing them to this repository.
Please consider using [semantic versioning](http://semver.org/) for release tags.

```
$ git checkout {some-release-commit}
$ git tag -a "v.0.1.0" -m "Short summary of the release."
$ git push -tags origin master
```

**Comment by mkroman** [comment]
[Done.](https://github.com/mkroman/rar/tags)

**Comment by johnjohndoe** [comment]
:+1:
